# docker build -f src/main/docker/Dockerfile.alpine -t cheat/quarkus-lightweight-container .
# docker run -it -d cheat/quarkus-lightweight-container bin/sh

FROM alpine:3.15

WORKDIR /work/

COPY --chown=1001:root target/*-runner /work/application

RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work

RUN apk add --update --no-cache \
    gcompat \
		ca-certificates \
		openssl \
		&& update-ca-certificates

EXPOSE 8080
USER 0

CMD ["./application", "-Dquarkus.http.host=0.0.0.0", "-Xms64m", "-Xmx128m", "-Xmn1m", "-H:+UseCompressedReferences"]
